# Generated by Django 5.0.6 on 2024-06-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='closed_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='working_hours',
            field=models.TextField(blank=True, null=True),
        ),
    ]
