# Generated by Django 5.0.6 on 2024-06-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contacts_closed_days_contacts_working_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Store employees', 'verbose_name_plural': 'Store employees'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='bio',
            field=models.TextField(max_length=255),
        ),
    ]
