# Generated by Django 5.0.6 on 2024-06-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_staff_options_alter_staff_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodcategory',
            options={'ordering': ['sort'], 'verbose_name': 'Product category', 'verbose_name_plural': 'Product categories'},
        ),
    ]
